version: '3.7'

services: 
  yse_pz: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    depends_on: 
      - "mysql"
    command: python3 manage.py runserver 0.0.0.0:8000

  mysql:
    image: mysql:5.7
    # command: 
    #   --default-authentication-plugin=mysql_native_password
    # restart: always
    volumes: 
      - ./mysql_data:/var/lib/mysql
      - ../data:/data
    environment: 
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'YSE'
    ports: 
      - "3306:3306"
      
